# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34bf46f7fe52a0ad0a395782459e1fce9f0a315796e75c3c3525a018730ea8e51f82b61a4fc28fb4aa331a894fab76a2cbccff585dafb2387b78c7020e9d0b85

test:
  secret_key_base: fc6f714fc51c65e55e579784a21e58c92683b5abc31c87db410c9f2e71e07c3179e95e41f289c34f06fd7f847f7d457044ba8c2f25f20dd9c06bfb7b194a2e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
